from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Mission(db.Model):
    __tablename__ = 'missions'
    mission_id = db.Column(db.Integer, primary_key=True)
    mission_date = db.Column(db.Date, nullable=False)
    theater_of_operations = db.Column(db.String(100))
    country = db.Column(db.String(100))
    air_force = db.Column(db.String(100))
    unit_id = db.Column(db.Integer)
    aircraft_series = db.Column(db.String(100))
    callsign = db.Column(db.String(100))
    mission_type = db.Column(db.String(100))
    takeoff_base = db.Column(db.String(255))
    takeoff_location = db.Column(db.String(255))
    takeoff_latitude = db.Column(db.Numeric(10, 6))
    takeoff_longitude = db.Column(db.Numeric(10, 6))
    target_id = db.Column(db.Integer)
    target_country = db.Column(db.String(100))
    target_city = db.Column(db.String(100))
    target_type = db.Column(db.String(100))
    target_industry = db.Column(db.String(255))
    target_priority = db.Column(db.Integer)
    target_latitude = db.Column(db.Numeric(10, 6))
    target_longitude = db.Column(db.Numeric(10, 6))
    altitude_hundreds_of_feet = db.Column(db.Numeric(7, 2))
    airborne_aircraft = db.Column(db.Numeric(4, 1))
    attacking_aircraft = db.Column(db.Integer)
    bombing_aircraft = db.Column(db.Integer)
    aircraft_returned = db.Column(db.Integer)
    aircraft_failed = db.Column(db.Integer)
    aircraft_damaged = db.Column(db.Integer)
    aircraft_lost = db.Column(db.Integer)
    high_explosives = db.Column(db.String(255))
    high_explosives_type = db.Column(db.String(255))
    high_explosives_weight_pounds = db.Column(db.String(25))
    high_explosives_weight_tons = db.Column(db.Numeric(10, 2))
    incendiary_devices = db.Column(db.String(255))
    incendiary_devices_type = db.Column(db.String(255))
    incendiary_devices_weight_pounds = db.Column(db.Numeric(10, 2))
    incendiary_devices_weight_tons = db.Column(db.Numeric(10, 2))
    fragmentation_devices = db.Column(db.String(255))
    fragmentation_devices_type = db.Column(db.String(255))
    fragmentation_devices_weight_pounds = db.Column(db.Numeric(10, 2))
    fragmentation_devices_weight_tons = db.Column(db.Numeric(10, 2))
    total_weight_pounds = db.Column(db.Numeric(10, 2))
    total_weight_tons = db.Column(db.Numeric(10, 2))
    time_over_target = db.Column(db.String(8))
    bomb_damage_assessment = db.Column(db.String(255))
    source_id = db.Column(db.Integer)